language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable"'

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - pecl install uopz
  - echo "extension = uopz.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover